spring:
   profiles:
      active:
      - dev
---
spring:
    profiles: dev #开发环境
    application:
        name: microservicecloud-config-yyg-dev
---
spring:
    profiles: test #测试环境
    application:
        name: microservicecloud-config-yyg-test
 #保证是UTF-8格式