server:
  port: 8001           
spring:
  profiles: dev
  application:
    name: springcloudsale-config-provider-client-8001                      
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          
    driver-class-name: org.gjt.mm.mysql.Driver            
    url: jdbc:mysql://localhost:3306/clouddb01      
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                        
      initial-size: 5                                       
      max-total: 5                                         
      max-wait-millis: 200                                  

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml       
  type-aliases-package: com.yyg.springcloud.entity  
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml      
      
eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id:  sale-provider-8001 
    prefer-ip-address: true     


info:
  app.name: yyg-microservicecloud
  company.name: www.yyg.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server: 
  port: 8001
spring:
  profiles: test
  application:
    name: springcloudsale-config-provider-client-8001                        
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource           
    driver-class-name: org.gjt.mm.mysql.Driver             
    url: jdbc:mysql://localhost:3306/clouddb02              
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                          
      initial-size: 5                                       
      max-total: 5                                          
      max-wait-millis: 200                                  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml       
  type-aliases-package: com.yyg.springcloud.entity    
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml 
 
eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id:  sale-provider-8001
    prefer-ip-address: true    


info:
  app.name: yyg-microservicecloud
  company.name: www.yyg.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

