
spring:
    profiles: dev
    application:
        name: springcloud-config-eureka-client-7002
eureka:
  instance:
    hostname: eureka7002.com 
  client:
    register-with-eureka: false 
    fetch-registry: false 
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
---
server:
  port: 7002
---
spring:
    profiles: dev
    application:
        name: springcloud-config-eureka-client-7002
eureka:
  instance:
    hostname: eureka7002.com 
  client:
    register-with-eureka: false 
    fetch-registry: false 
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/